// bytecodes: 128

static const label_t bytecodeLabels[] PROGMEM = {
	LABEL(INVOKESHORT),            //   0 processing_hardware_arduino_cores_arduino_Arduino_delayMicroseconds_IV
	LABEL(INVOKESHORT),            //   1 processing_hardware_arduino_cores_arduino_Arduino_digitalWrite_IIV
	LABEL(INVOKESHORT),            //   2 arduino_libraries_liquidcrystal_LiquidCrystal_command_BV
	LABEL(INVOKESHORT),            //   3 processing_hardware_arduino_cores_arduino_Arduino_pinMode_IIV
	LABEL(INVOKESHORT),            //   4 java_lang_Object__init__V
	LABEL(INVOKESHORT),            //   5 processing_hardware_arduino_cores_arduino_Print__init__V
	LABEL(INVOKESHORT),            //   6 arduino_libraries_liquidcrystal_LiquidCrystal_send_BBV
	LABEL(INVOKESHORT),            //   7 arduino_libraries_liquidcrystal_LiquidCrystalHelloWorld_setup_V
	LABEL(INVOKESHORT),            //   8 arduino_libraries_liquidcrystal_LiquidCrystalHelloWorld_loop_V
	LABEL(INVOKESHORT),            //   9 haiku_avr_lib_arduino_HaikuMicroKernelProcessing_init_V
	LABEL(INVOKESHORT),            //  10 arduino_libraries_liquidcrystal_LiquidCrystal__init__BBBBBBV
	LABEL(INVOKESHORT),            //  11 java_lang_Throwable__init__Ljava_lang_String_V
	LABEL(INVOKESHORT),            //  12 java_lang_Thread_setStateAndSwitch_II
	LABEL(INVOKESHORT),            //  13 java_lang_OutOfMemoryError__init__Ljava_lang_String_V
	LABEL(INVOKESHORT),            //  14 java_lang_Error__init__Ljava_lang_String_V
	LABEL(INVOKESHORT),            //  15 java_lang_Thread_currentThread_Ljava_lang_Thread
	LABEL(INVOKESHORT),            //  16 haiku_vm_MicroKernel_clinitHaikuMagic_V
	LABEL(INVOKESHORT),            //  17 processing_hardware_arduino_cores_arduino_Stream__init__V
	LABEL(INVOKESHORT),            //  18 arduino_libraries_liquidcrystal_LiquidCrystal_init_BBBBBBBBBBBBV
	LABEL(INVOKESHORT),            //  19 processing_hardware_arduino_cores_arduino_Arduino_millis_J
	LABEL(INVOKESHORT),            //  20 processing_hardware_arduino_cores_arduino_ArduinoImpl_millis_J
	LABEL(INVOKESHORT),            //  21 processing_hardware_arduino_cores_arduino_HardwareSerial__init__V
	LABEL(INVOKESHORT),            //  22 processing_hardware_arduino_cores_arduino_Print_printNumber_JIV
	LABEL(INVOKESHORT),            //  23 processing_hardware_arduino_cores_arduino_ArduinoImpl_digitalWrite_BBV
	LABEL(INVOKESHORT),            //  24 processing_hardware_arduino_cores_arduino_ArduinoImpl_delayMicroseconds_IV
	LABEL(INVOKESHORT),            //  25 processing_hardware_arduino_cores_arduino_ArduinoImpl_pinMode_BBV
	LABEL(INVOKESHORT),            //  26 processing_hardware_arduino_cores_arduino_HardwareSerialImpl_write_BB
	LABEL(INVOKESHORT),            //  27 arduino_libraries_liquidcrystal_LiquidCrystal_write8bits_BV
	LABEL(INVOKESHORT),            //  28 arduino_libraries_liquidcrystal_LiquidCrystal_write4bits_BV
	LABEL(INVOKESHORT),            //  29 processing_hardware_arduino_cores_arduino_HardwareSerial_write_BB
	LABEL(INVOKESHORT),            //  30 arduino_libraries_liquidcrystal_LiquidCrystal_setCursor_BBV
	LABEL(INVOKESHORT),            //  31 processing_hardware_arduino_cores_arduino_Print_print_CV
	LABEL(INVOKESHORT),            //  32 processing_hardware_arduino_cores_arduino_Arduino__clinit__V
	LABEL(INVOKESHORT),            //  33 arduino_libraries_liquidcrystal_LiquidCrystal_begin_BBBV
	LABEL(INVOKESHORT),            //  34 main_YLjava_lang_String
	LABEL(INVOKESHORT),            //  35 arduino_libraries_liquidcrystal_LiquidCrystal_begin_BBV
	LABEL(INVOKESHORT),            //  36 arduino_libraries_liquidcrystal_LiquidCrystal_clear_V
	LABEL(INVOKESHORT),            //  37 java_lang_String_charAt_IC
	LABEL(INVOKESHORT),            //  38 haiku_vm_MicroKernel__clinit__V
	LABEL(INVOKESHORT),            //  39 processing_hardware_arduino_cores_arduino_Print__clinit__V
	LABEL(INVOKESHORT),            //  40 java_lang_Throwable_fillInStackTrace_Ljava_lang_Throwable
	LABEL(INVOKESHORT),            //  41 arduino_libraries_liquidcrystal_LiquidCrystal_write_BB
	LABEL(INVOKESHORT),            //  42 arduino_libraries_liquidcrystal_LiquidCrystalHelloWorld__clinit__V
	LABEL(INVOKESHORT),            //  43 arduino_libraries_liquidcrystal_LiquidCrystal_display_V
	LABEL(INVOKESHORT),            //  44 arduino_libraries_liquidcrystal_LiquidCrystal_pulseEnable_V
	LABEL(INVOKESHORT),            //  45 java_lang_Thread_stop_V
	LABEL(INVOKESHORT),            //  46 processing_hardware_arduino_cores_arduino_Print_print_Ljava_lang_String_V
	LABEL(INVOKESHORT),            //  47 java_lang_String_length_I
	LABEL(INVOKESHORT),            //  48 processing_hardware_arduino_cores_arduino_Print_print_JV
	LABEL(ALOAD_0),                //  49 ALOAD_1
	LABEL(IFEQ),                   //  50 IFEQ
	LABEL(ALOAD_0),                //  51 ALOAD_3
	LABEL(IF_ICMPEQ),              //  52 IF_ICMPLT
	LABEL(IFEQ),                   //  53 IFNE
	LABEL(IFEQ),                   //  54 IFLE
	LABEL(LDC2_W_L),               //  55 LDC2_W_L
	LABEL(ALOAD_0),                //  56 ALOAD_0
	LABEL(ASTORE_0),               //  57 ASTORE_1
	LABEL(IF_ACMPEQ),              //  58 IF_ACMPEQ
	LABEL(ASTORE_0),               //  59 ASTORE_3
	LABEL(ALOAD),                  //  60 ALOAD
	LABEL(IF_ICMPEQ),              //  61 IF_ICMPNE
	LABEL(IF_ICMPEQ),              //  62 IF_ICMPLE
	LABEL(ARETURN),                //  63 ARETURN
	LABEL(LCONST_0),               //  64 LCONST_0
	LABEL(LLOAD_0),                //  65 LLOAD_1
	LABEL(IF_ICMPEQ),              //  66 IF_ICMPEQ
	LABEL(IFEQ),                   //  67 IFGE
	LABEL(ARRAYLENGTH),            //  68 ARRAYLENGTH
	LABEL(LDC_S),                  //  69 LDC_S
	LABEL(LDC_S),                  //  70 LDC_I
	LABEL(ASTORE),                 //  71 ASTORE
	LABEL(BALOAD),                 //  72 BALOAD
	LABEL(LSTORE_0),               //  73 LSTORE_1
	LABEL(FSTORE_0),               //  74 ISTORE_2
	LABEL(IF_ICMPEQ),              //  75 IF_ICMPGE
	LABEL(BASTORE),                //  76 BASTORE
	LABEL(BIPUSH),                 //  77 BIPUSH
	LABEL(CALOAD),                 //  78 CALOAD
	LABEL(DUP),                    //  79 DUP
	LABEL(GETFIELD_B),             //  80 GETFIELD_B
	LABEL(GETFIELD_I),             //  81 GETFIELD_I
	LABEL(GETFIELD_L),             //  82 GETFIELD_L
	LABEL(GETSTATIC_L),            //  83 GETSTATIC_L
	LABEL(GOTO),                   //  84 GOTO
	LABEL(I2B),                    //  85 I2B
	LABEL(I2C),                    //  86 I2C
	LABEL(I2L),                    //  87 I2L
	LABEL(IADD),                   //  88 IADD
	LABEL(IAND),                   //  89 IAND
	LABEL(ICONST_0),               //  90 ICONST_0
	LABEL(ICONST_1),               //  91 ICONST_1
	LABEL(ICONST_2),               //  92 ICONST_2
	LABEL(ICONST_3),               //  93 ICONST_3
	LABEL(ICONST_4),               //  94 ICONST_4
	LABEL(ICONST_5),               //  95 ICONST_5
	LABEL(ICONST_M1),              //  96 ICONST_M1
	LABEL(IINC),                   //  97 IINC
	LABEL(IINC1),                  //  98 IINC1
	LABEL(ILOAD),                  //  99 ILOAD
	LABEL(ILOAD_0),                // 100 ILOAD_0
	LABEL(ILOAD_1),                // 101 ILOAD_1
	LABEL(ILOAD_2),                // 102 ILOAD_2
	LABEL(ILOAD_3),                // 103 ILOAD_3
	LABEL(INVOKESPECIAL),          // 104 INVOKESTATIC
	LABEL(INVOKEVIRTUAL),          // 105 INVOKEVIRTUAL
	LABEL(IOR),                    // 106 IOR
	LABEL(ARETURN),                // 107 IRETURN
	LABEL(ISHR),                   // 108 ISHR
	LABEL(FSTORE),                 // 109 ISTORE
	LABEL(ISUB),                   // 110 ISUB
	LABEL(L2I),                    // 111 L2I
	LABEL(LCMP),                   // 112 LCMP
	LABEL(LDIV),                   // 113 LDIV
	LABEL(LNEG),                   // 114 LNEG
	LABEL(LREM),                   // 115 LREM
	LABEL(DRETURN),                // 116 LRETURN
	LABEL(NEW),                    // 117 NEW
	LABEL(ANEWARRAY),              // 118 NEWARRAY
	LABEL(POP),                    // 119 POP
	LABEL(PUTFIELD_B),             // 120 PUTFIELD_B
	LABEL(PUTFIELD_C),             // 121 PUTFIELD_C
	LABEL(PUTFIELD_I),             // 122 PUTFIELD_I
	LABEL(PUTFIELD_L),             // 123 PUTFIELD_L
	LABEL(PUTSTATIC_I),            // 124 PUTSTATIC_I
	LABEL(PUTSTATIC_L),            // 125 PUTSTATIC_L
	LABEL(RETURN),                 // 126 RETURN
	LABEL(SIPUSH),                 // 127 SIPUSH
};
